### ISSUE TITLE
Just discovered the vercon 32 for the first time off of a YouTube channel I watch saying that they updated the new core on retroarch for version 1 8.0 now I am going to play jellyfish your game here and it's going to be the first work on 32 title I play :]

### ISSUE THREAD

**Issue by purrpgoddpeebles** [vircon32/CommunityContent#17]

**Comment by vircon32** [comment]
Hi purrpgoddpeebles. It's great you like the console, I hope you have a great time with it. The jellyfish game is not actually mine, it was made by TheR.

I'm closing this now, since a code issue is not really the place for a conversation. If you want to talk you can find me at YouTube (Vircon32), Twitter (@vircon32) and Discord (I have a Vircon32 channel at the [Fantasy Consoles 2.0](https://discord.com/invite/jcT9CXDgHB) server).
